DROP VIEW APP.MAANDVERBRUIK_EXTRA;

CREATE VIEW APP.MAANDVERBRUIK_EXTRA (
	  ID
	, JAAR
	, MAAND
	, ID_METERSOORT
	, VERBRUIK
	, AVERAGE
	, DELTA
) AS (
	SELECT 
 	  m.ID
	, m.JAAR
	, m.MAAND
	, m.ID_METERSOORT
	, m.VERBRUIK
	, av.average
	, m.VERBRUIK-av.AVERAGE AS delta
	FROM APP.MAANDVERBRUIK M
	LEFT JOIN APP.MAANDVERBRUIK_AVG av
	ON m.ID_METERSOORT = av.ID_METERSOORT
	AND m.MAAND = av.MAAND
	ORDER BY JAAR, MAAND, ID_METERSOORT
);